### ISSUE TITLE
Roadmap for Fundamentals

### ISSUE THREAD

**Issue by Teddy-van-Jerry** [Teddy-van-Jerry/termipaper#1]
TermiPaper is still in development. The following roadmap are subject to change.

- [x] **Configuration**: https://github.com/Teddy-van-Jerry/termipaper/commit/371e9e1863abb267a25c62a6b1f7505da4df2162
- [x] **Paper Management**
  - [x] Add paper: https://github.com/Teddy-van-Jerry/termipaper/commit/edde53ca7625f05c908a960badf49aef62c9a322
  - [x] Remove paper: https://github.com/Teddy-van-Jerry/termipaper/commit/10e2361eacd619ae5a48a87264b5483a4fe7fced
  - [x] Update paper: https://github.com/Teddy-van-Jerry/termipaper/commit/3a3c05e0c3f33a8c142bb68b4e32ad3b94515e6d
  - [x] Metadata: https://github.com/Teddy-van-Jerry/termipaper/commit/e4ec6bef7f2ba11a6ed88363e7a3edcde9c7257c
- [ ] **Citation Generation**
  - [ ] BibTeX
- [ ] **Search**
  - [ ] By Metadata
  - [ ] By Content
- [ ] **Sharing**
- [x] *Test Script*: https://github.com/Teddy-van-Jerry/termipaper/commit/2a130fe16cf27d0fb9f1d7d0d6c583890067e8c5
- [x] *Project Website*: https://github.com/Teddy-van-Jerry/termipaper.wqzhao.org/commit/5f7e048126070959d0412ecdb7c5f2bdd876bc0e
- [x] *Rust Crate Publication*: https://crates.io/crates/termipaper
